QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    backend/json-develop/docs/examples/README.cpp \
    backend/json-develop/docs/examples/accept__string.cpp \
    backend/json-develop/docs/examples/array.cpp \
    backend/json-develop/docs/examples/array_t.cpp \
    backend/json-develop/docs/examples/at__json_pointer.cpp \
    backend/json-develop/docs/examples/at__json_pointer_const.cpp \
    backend/json-develop/docs/examples/at__keytype.c++17.cpp \
    backend/json-develop/docs/examples/at__keytype_const.c++17.cpp \
    backend/json-develop/docs/examples/at__object_t_key_type.cpp \
    backend/json-develop/docs/examples/at__object_t_key_type_const.cpp \
    backend/json-develop/docs/examples/at__size_type.cpp \
    backend/json-develop/docs/examples/at__size_type_const.cpp \
    backend/json-develop/docs/examples/back.cpp \
    backend/json-develop/docs/examples/basic_json__CompatibleType.cpp \
    backend/json-develop/docs/examples/basic_json__InputIt_InputIt.cpp \
    backend/json-develop/docs/examples/basic_json__basic_json.cpp \
    backend/json-develop/docs/examples/basic_json__copyassignment.cpp \
    backend/json-develop/docs/examples/basic_json__list_init_t.cpp \
    backend/json-develop/docs/examples/basic_json__moveconstructor.cpp \
    backend/json-develop/docs/examples/basic_json__nullptr_t.cpp \
    backend/json-develop/docs/examples/basic_json__size_type_basic_json.cpp \
    backend/json-develop/docs/examples/basic_json__value_t.cpp \
    backend/json-develop/docs/examples/begin.cpp \
    backend/json-develop/docs/examples/binary.cpp \
    backend/json-develop/docs/examples/binary_t.cpp \
    backend/json-develop/docs/examples/boolean_t.cpp \
    backend/json-develop/docs/examples/byte_container_with_subtype__byte_container_with_subtype.cpp \
    backend/json-develop/docs/examples/byte_container_with_subtype__clear_subtype.cpp \
    backend/json-develop/docs/examples/byte_container_with_subtype__has_subtype.cpp \
    backend/json-develop/docs/examples/byte_container_with_subtype__set_subtype.cpp \
    backend/json-develop/docs/examples/byte_container_with_subtype__subtype.cpp \
    backend/json-develop/docs/examples/cbegin.cpp \
    backend/json-develop/docs/examples/cbor_tag_handler_t.cpp \
    backend/json-develop/docs/examples/cend.cpp \
    backend/json-develop/docs/examples/clear.cpp \
    backend/json-develop/docs/examples/contains__json_pointer.cpp \
    backend/json-develop/docs/examples/contains__keytype.c++17.cpp \
    backend/json-develop/docs/examples/contains__object_t_key_type.cpp \
    backend/json-develop/docs/examples/count__keytype.c++17.cpp \
    backend/json-develop/docs/examples/count__object_t_key_type.cpp \
    backend/json-develop/docs/examples/crbegin.cpp \
    backend/json-develop/docs/examples/crend.cpp \
    backend/json-develop/docs/examples/default_object_comparator_t.cpp \
    backend/json-develop/docs/examples/diagnostics_extended.cpp \
    backend/json-develop/docs/examples/diagnostics_standard.cpp \
    backend/json-develop/docs/examples/diff.cpp \
    backend/json-develop/docs/examples/dump.cpp \
    backend/json-develop/docs/examples/emplace.cpp \
    backend/json-develop/docs/examples/emplace_back.cpp \
    backend/json-develop/docs/examples/empty.cpp \
    backend/json-develop/docs/examples/end.cpp \
    backend/json-develop/docs/examples/erase__IteratorType.cpp \
    backend/json-develop/docs/examples/erase__IteratorType_IteratorType.cpp \
    backend/json-develop/docs/examples/erase__keytype.c++17.cpp \
    backend/json-develop/docs/examples/erase__object_t_key_type.cpp \
    backend/json-develop/docs/examples/erase__size_type.cpp \
    backend/json-develop/docs/examples/error_handler_t.cpp \
    backend/json-develop/docs/examples/exception.cpp \
    backend/json-develop/docs/examples/find__keytype.c++17.cpp \
    backend/json-develop/docs/examples/find__object_t_key_type.cpp \
    backend/json-develop/docs/examples/flatten.cpp \
    backend/json-develop/docs/examples/from_bjdata.cpp \
    backend/json-develop/docs/examples/from_bson.cpp \
    backend/json-develop/docs/examples/from_cbor.cpp \
    backend/json-develop/docs/examples/from_json__default_constructible.cpp \
    backend/json-develop/docs/examples/from_json__non_default_constructible.cpp \
    backend/json-develop/docs/examples/from_msgpack.cpp \
    backend/json-develop/docs/examples/from_ubjson.cpp \
    backend/json-develop/docs/examples/front.cpp \
    backend/json-develop/docs/examples/get__PointerType.cpp \
    backend/json-develop/docs/examples/get__ValueType_const.cpp \
    backend/json-develop/docs/examples/get_allocator.cpp \
    backend/json-develop/docs/examples/get_binary.cpp \
    backend/json-develop/docs/examples/get_ptr.cpp \
    backend/json-develop/docs/examples/get_ref.cpp \
    backend/json-develop/docs/examples/get_to.cpp \
    backend/json-develop/docs/examples/insert.cpp \
    backend/json-develop/docs/examples/insert__count.cpp \
    backend/json-develop/docs/examples/insert__ilist.cpp \
    backend/json-develop/docs/examples/insert__range.cpp \
    backend/json-develop/docs/examples/insert__range_object.cpp \
    backend/json-develop/docs/examples/invalid_iterator.cpp \
    backend/json-develop/docs/examples/is_array.cpp \
    backend/json-develop/docs/examples/is_binary.cpp \
    backend/json-develop/docs/examples/is_boolean.cpp \
    backend/json-develop/docs/examples/is_discarded.cpp \
    backend/json-develop/docs/examples/is_null.cpp \
    backend/json-develop/docs/examples/is_number.cpp \
    backend/json-develop/docs/examples/is_number_float.cpp \
    backend/json-develop/docs/examples/is_number_integer.cpp \
    backend/json-develop/docs/examples/is_number_unsigned.cpp \
    backend/json-develop/docs/examples/is_object.cpp \
    backend/json-develop/docs/examples/is_primitive.cpp \
    backend/json-develop/docs/examples/is_string.cpp \
    backend/json-develop/docs/examples/is_structured.cpp \
    backend/json-develop/docs/examples/items.cpp \
    backend/json-develop/docs/examples/json_base_class_t.cpp \
    backend/json-develop/docs/examples/json_lines.cpp \
    backend/json-develop/docs/examples/json_pointer.cpp \
    backend/json-develop/docs/examples/json_pointer__back.cpp \
    backend/json-develop/docs/examples/json_pointer__empty.cpp \
    backend/json-develop/docs/examples/json_pointer__operator__equal.cpp \
    backend/json-develop/docs/examples/json_pointer__operator__equal_stringtype.cpp \
    backend/json-develop/docs/examples/json_pointer__operator__notequal.cpp \
    backend/json-develop/docs/examples/json_pointer__operator__notequal_stringtype.cpp \
    backend/json-develop/docs/examples/json_pointer__operator_add.cpp \
    backend/json-develop/docs/examples/json_pointer__operator_add_binary.cpp \
    backend/json-develop/docs/examples/json_pointer__operator_string_t.cpp \
    backend/json-develop/docs/examples/json_pointer__parent_pointer.cpp \
    backend/json-develop/docs/examples/json_pointer__pop_back.cpp \
    backend/json-develop/docs/examples/json_pointer__push_back.cpp \
    backend/json-develop/docs/examples/json_pointer__string_t.cpp \
    backend/json-develop/docs/examples/json_pointer__to_string.cpp \
    backend/json-develop/docs/examples/max_size.cpp \
    backend/json-develop/docs/examples/merge_patch.cpp \
    backend/json-develop/docs/examples/meta.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_explicit.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_macro.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_only_serialize_explicit.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_only_serialize_macro.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_with_default_explicit.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_with_default_macro.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_explicit.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_macro.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_only_serialize_explicit.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_only_serialize_macro.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_with_default_explicit.cpp \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_with_default_macro.cpp \
    backend/json-develop/docs/examples/nlohmann_json_namespace.cpp \
    backend/json-develop/docs/examples/nlohmann_json_namespace_begin.c++17.cpp \
    backend/json-develop/docs/examples/nlohmann_json_namespace_no_version.cpp \
    backend/json-develop/docs/examples/nlohmann_json_serialize_enum.cpp \
    backend/json-develop/docs/examples/nlohmann_json_serialize_enum_2.cpp \
    backend/json-develop/docs/examples/nlohmann_json_version.cpp \
    backend/json-develop/docs/examples/number_float_t.cpp \
    backend/json-develop/docs/examples/number_integer_t.cpp \
    backend/json-develop/docs/examples/number_unsigned_t.cpp \
    backend/json-develop/docs/examples/object.cpp \
    backend/json-develop/docs/examples/object_comparator_t.cpp \
    backend/json-develop/docs/examples/object_t.cpp \
    backend/json-develop/docs/examples/operator__ValueType.cpp \
    backend/json-develop/docs/examples/operator__equal.cpp \
    backend/json-develop/docs/examples/operator__equal__nullptr_t.cpp \
    backend/json-develop/docs/examples/operator__equal__specializations.cpp \
    backend/json-develop/docs/examples/operator__greater.cpp \
    backend/json-develop/docs/examples/operator__greaterequal.cpp \
    backend/json-develop/docs/examples/operator__less.cpp \
    backend/json-develop/docs/examples/operator__lessequal.cpp \
    backend/json-develop/docs/examples/operator__notequal.cpp \
    backend/json-develop/docs/examples/operator__notequal__nullptr_t.cpp \
    backend/json-develop/docs/examples/operator__value_t.cpp \
    backend/json-develop/docs/examples/operator_array__json_pointer.cpp \
    backend/json-develop/docs/examples/operator_array__json_pointer_const.cpp \
    backend/json-develop/docs/examples/operator_array__keytype.c++17.cpp \
    backend/json-develop/docs/examples/operator_array__keytype_const.c++17.cpp \
    backend/json-develop/docs/examples/operator_array__object_t_key_type.cpp \
    backend/json-develop/docs/examples/operator_array__object_t_key_type_const.cpp \
    backend/json-develop/docs/examples/operator_array__size_type.cpp \
    backend/json-develop/docs/examples/operator_array__size_type_const.cpp \
    backend/json-develop/docs/examples/operator_deserialize.cpp \
    backend/json-develop/docs/examples/operator_literal_json.cpp \
    backend/json-develop/docs/examples/operator_literal_json_pointer.cpp \
    backend/json-develop/docs/examples/operator_ltlt__basic_json.cpp \
    backend/json-develop/docs/examples/operator_ltlt__json_pointer.cpp \
    backend/json-develop/docs/examples/operator_spaceship__const_reference.c++20.cpp \
    backend/json-develop/docs/examples/operator_spaceship__scalartype.c++20.cpp \
    backend/json-develop/docs/examples/ordered_json.cpp \
    backend/json-develop/docs/examples/ordered_map.cpp \
    backend/json-develop/docs/examples/other_error.cpp \
    backend/json-develop/docs/examples/out_of_range.cpp \
    backend/json-develop/docs/examples/parse__allow_exceptions.cpp \
    backend/json-develop/docs/examples/parse__array__parser_callback_t.cpp \
    backend/json-develop/docs/examples/parse__contiguouscontainer__parser_callback_t.cpp \
    backend/json-develop/docs/examples/parse__istream__parser_callback_t.cpp \
    backend/json-develop/docs/examples/parse__iterator_pair.cpp \
    backend/json-develop/docs/examples/parse__pointers.cpp \
    backend/json-develop/docs/examples/parse__string__parser_callback_t.cpp \
    backend/json-develop/docs/examples/parse_error.cpp \
    backend/json-develop/docs/examples/patch.cpp \
    backend/json-develop/docs/examples/patch_inplace.cpp \
    backend/json-develop/docs/examples/push_back.cpp \
    backend/json-develop/docs/examples/push_back__initializer_list.cpp \
    backend/json-develop/docs/examples/push_back__object_t__value.cpp \
    backend/json-develop/docs/examples/rbegin.cpp \
    backend/json-develop/docs/examples/rend.cpp \
    backend/json-develop/docs/examples/sax_parse.cpp \
    backend/json-develop/docs/examples/sax_parse__binary.cpp \
    backend/json-develop/docs/examples/size.cpp \
    backend/json-develop/docs/examples/std_hash.cpp \
    backend/json-develop/docs/examples/std_swap.cpp \
    backend/json-develop/docs/examples/string_t.cpp \
    backend/json-develop/docs/examples/swap__array_t.cpp \
    backend/json-develop/docs/examples/swap__binary_t.cpp \
    backend/json-develop/docs/examples/swap__object_t.cpp \
    backend/json-develop/docs/examples/swap__reference.cpp \
    backend/json-develop/docs/examples/swap__string_t.cpp \
    backend/json-develop/docs/examples/to_bjdata.cpp \
    backend/json-develop/docs/examples/to_bson.cpp \
    backend/json-develop/docs/examples/to_cbor.cpp \
    backend/json-develop/docs/examples/to_json.cpp \
    backend/json-develop/docs/examples/to_msgpack.cpp \
    backend/json-develop/docs/examples/to_string.cpp \
    backend/json-develop/docs/examples/to_ubjson.cpp \
    backend/json-develop/docs/examples/type.cpp \
    backend/json-develop/docs/examples/type_error.cpp \
    backend/json-develop/docs/examples/type_name.cpp \
    backend/json-develop/docs/examples/unflatten.cpp \
    backend/json-develop/docs/examples/update.cpp \
    backend/json-develop/docs/examples/update__range.cpp \
    backend/json-develop/docs/examples/value__json_ptr.cpp \
    backend/json-develop/docs/examples/value__keytype.c++17.cpp \
    backend/json-develop/docs/examples/value__object_t_key_type.cpp \
    backend/json-develop/docs/mkdocs/docs/integration/conan/example.cpp \
    backend/json-develop/docs/mkdocs/docs/integration/example.cpp \
    backend/json-develop/docs/mkdocs/docs/integration/vcpkg/example.cpp \
    backend/json-develop/tests/abi/config/custom.cpp \
    backend/json-develop/tests/abi/config/default.cpp \
    backend/json-develop/tests/abi/config/noversion.cpp \
    backend/json-develop/tests/abi/diag/diag.cpp \
    backend/json-develop/tests/abi/diag/diag_off.cpp \
    backend/json-develop/tests/abi/diag/diag_on.cpp \
    backend/json-develop/tests/abi/inline_ns/use_current.cpp \
    backend/json-develop/tests/abi/inline_ns/use_v3_10_5.cpp \
    backend/json-develop/tests/abi/main.cpp \
    backend/json-develop/tests/benchmarks/src/benchmarks.cpp \
    backend/json-develop/tests/cmake_add_subdirectory/project/main.cpp \
    backend/json-develop/tests/cmake_fetch_content/project/main.cpp \
    backend/json-develop/tests/cmake_fetch_content2/project/main.cpp \
    backend/json-develop/tests/cmake_import/project/main.cpp \
    backend/json-develop/tests/cmake_import_minver/project/main.cpp \
    backend/json-develop/tests/cmake_target_include_directories/project/Bar.cpp \
    backend/json-develop/tests/cmake_target_include_directories/project/Foo.cpp \
    backend/json-develop/tests/cmake_target_include_directories/project/main.cpp \
    backend/json-develop/tests/src/fuzzer-driver_afl.cpp \
    backend/json-develop/tests/src/fuzzer-parse_bjdata.cpp \
    backend/json-develop/tests/src/fuzzer-parse_bson.cpp \
    backend/json-develop/tests/src/fuzzer-parse_cbor.cpp \
    backend/json-develop/tests/src/fuzzer-parse_json.cpp \
    backend/json-develop/tests/src/fuzzer-parse_msgpack.cpp \
    backend/json-develop/tests/src/fuzzer-parse_ubjson.cpp \
    backend/json-develop/tests/src/unit-32bit.cpp \
    backend/json-develop/tests/src/unit-algorithms.cpp \
    backend/json-develop/tests/src/unit-allocator.cpp \
    backend/json-develop/tests/src/unit-alt-string.cpp \
    backend/json-develop/tests/src/unit-assert_macro.cpp \
    backend/json-develop/tests/src/unit-binary_formats.cpp \
    backend/json-develop/tests/src/unit-bjdata.cpp \
    backend/json-develop/tests/src/unit-bson.cpp \
    backend/json-develop/tests/src/unit-byte_container_with_subtype.cpp \
    backend/json-develop/tests/src/unit-capacity.cpp \
    backend/json-develop/tests/src/unit-cbor.cpp \
    backend/json-develop/tests/src/unit-class_const_iterator.cpp \
    backend/json-develop/tests/src/unit-class_iterator.cpp \
    backend/json-develop/tests/src/unit-class_lexer.cpp \
    backend/json-develop/tests/src/unit-class_parser.cpp \
    backend/json-develop/tests/src/unit-comparison.cpp \
    backend/json-develop/tests/src/unit-concepts.cpp \
    backend/json-develop/tests/src/unit-constructor1.cpp \
    backend/json-develop/tests/src/unit-constructor2.cpp \
    backend/json-develop/tests/src/unit-convenience.cpp \
    backend/json-develop/tests/src/unit-conversions.cpp \
    backend/json-develop/tests/src/unit-custom-base-class.cpp \
    backend/json-develop/tests/src/unit-deserialization.cpp \
    backend/json-develop/tests/src/unit-diagnostics.cpp \
    backend/json-develop/tests/src/unit-disabled_exceptions.cpp \
    backend/json-develop/tests/src/unit-element_access1.cpp \
    backend/json-develop/tests/src/unit-element_access2.cpp \
    backend/json-develop/tests/src/unit-hash.cpp \
    backend/json-develop/tests/src/unit-inspection.cpp \
    backend/json-develop/tests/src/unit-items.cpp \
    backend/json-develop/tests/src/unit-iterators1.cpp \
    backend/json-develop/tests/src/unit-iterators2.cpp \
    backend/json-develop/tests/src/unit-json_patch.cpp \
    backend/json-develop/tests/src/unit-json_pointer.cpp \
    backend/json-develop/tests/src/unit-large_json.cpp \
    backend/json-develop/tests/src/unit-merge_patch.cpp \
    backend/json-develop/tests/src/unit-meta.cpp \
    backend/json-develop/tests/src/unit-modifiers.cpp \
    backend/json-develop/tests/src/unit-msgpack.cpp \
    backend/json-develop/tests/src/unit-no-mem-leak-on-adl-serialize.cpp \
    backend/json-develop/tests/src/unit-noexcept.cpp \
    backend/json-develop/tests/src/unit-ordered_json.cpp \
    backend/json-develop/tests/src/unit-ordered_map.cpp \
    backend/json-develop/tests/src/unit-pointer_access.cpp \
    backend/json-develop/tests/src/unit-readme.cpp \
    backend/json-develop/tests/src/unit-reference_access.cpp \
    backend/json-develop/tests/src/unit-regression1.cpp \
    backend/json-develop/tests/src/unit-regression2.cpp \
    backend/json-develop/tests/src/unit-serialization.cpp \
    backend/json-develop/tests/src/unit-testsuites.cpp \
    backend/json-develop/tests/src/unit-to_chars.cpp \
    backend/json-develop/tests/src/unit-type_traits.cpp \
    backend/json-develop/tests/src/unit-ubjson.cpp \
    backend/json-develop/tests/src/unit-udl.cpp \
    backend/json-develop/tests/src/unit-udt.cpp \
    backend/json-develop/tests/src/unit-udt_macro.cpp \
    backend/json-develop/tests/src/unit-unicode1.cpp \
    backend/json-develop/tests/src/unit-unicode2.cpp \
    backend/json-develop/tests/src/unit-unicode3.cpp \
    backend/json-develop/tests/src/unit-unicode4.cpp \
    backend/json-develop/tests/src/unit-unicode5.cpp \
    backend/json-develop/tests/src/unit-user_defined_input.cpp \
    backend/json-develop/tests/src/unit-windows_h.cpp \
    backend/json-develop/tests/src/unit-wstring.cpp \
    backend/json-develop/tests/src/unit.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerCrossOver.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerDriver.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerExtFunctionsDlsym.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerExtFunctionsWeak.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerExtFunctionsWeakAlias.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerIO.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerIOPosix.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerIOWindows.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerLoop.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerMain.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerMerge.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerMutate.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerSHA1.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerTracePC.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerTraceState.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerUtil.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerUtilDarwin.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerUtilLinux.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerUtilPosix.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerUtilWindows.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/afl/afl_driver.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/standalone/StandaloneFuzzTargetMain.c \
    backend/json-develop/tests/thirdparty/Fuzzer/test/AFLDriverTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/AbsNegAndConstant64Test.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/AbsNegAndConstantTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/AccumulateAllocationsTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/BufferOverflowOnInput.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/CallerCalleeTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/CounterTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/CustomCrossOverTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/CustomMutatorTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/DSO1.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/DSO2.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/DSOTestExtra.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/DSOTestMain.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/DivTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/EmptyTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/FourIndependentBranchesTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/FullCoverageSetTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/FuzzerUnittest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/InitializeTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/LeakTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/LeakTimeoutTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/LoadTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/MemcmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/NthRunCrashTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/NullDerefOnEmptyTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/NullDerefTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/OneHugeAllocTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/OutOfMemorySingleLargeMallocTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/OutOfMemoryTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/RepeatedBytesTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/RepeatedMemcmp.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/ShrinkControlFlowTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/ShrinkValueProfileTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SignedIntOverflowTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SimpleCmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SimpleDictionaryTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SimpleHashTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SimpleTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SimpleThreadedTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SingleMemcmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SingleStrcmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SingleStrncmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SpamyTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/StrcmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/StrncmpOOBTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/StrncmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/StrstrTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SwapCmpTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/Switch2Test.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/SwitchTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/ThreadedLeakTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/ThreadedTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/TimeoutEmptyTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/TimeoutTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/TraceMallocTest.cpp \
    backend/json-develop/tests/thirdparty/Fuzzer/test/UninstrumentedTest.cpp \
    backend/json-develop/tools/macro_builder/main.cpp \
    frontend/searchMenu.cpp \
    frontend/layoutswidget.cpp \
    frontend/menubar.cpp \
    main.cpp \
    frontend/mainwindow.cpp \
    frontend/simulation.cpp \
    frontend/editor.cpp \
    frontend/sensorPanel.cpp \
    backend/sensors.cpp \

HEADERS += \
    backend/json-develop/include/nlohmann/adl_serializer.hpp \
    backend/json-develop/include/nlohmann/byte_container_with_subtype.hpp \
    backend/json-develop/include/nlohmann/detail/abi_macros.hpp \
    backend/json-develop/include/nlohmann/detail/conversions/from_json.hpp \
    backend/json-develop/include/nlohmann/detail/conversions/to_chars.hpp \
    backend/json-develop/include/nlohmann/detail/conversions/to_json.hpp \
    backend/json-develop/include/nlohmann/detail/exceptions.hpp \
    backend/json-develop/include/nlohmann/detail/hash.hpp \
    backend/json-develop/include/nlohmann/detail/input/binary_reader.hpp \
    backend/json-develop/include/nlohmann/detail/input/input_adapters.hpp \
    backend/json-develop/include/nlohmann/detail/input/json_sax.hpp \
    backend/json-develop/include/nlohmann/detail/input/lexer.hpp \
    backend/json-develop/include/nlohmann/detail/input/parser.hpp \
    backend/json-develop/include/nlohmann/detail/input/position_t.hpp \
    backend/json-develop/include/nlohmann/detail/iterators/internal_iterator.hpp \
    backend/json-develop/include/nlohmann/detail/iterators/iter_impl.hpp \
    backend/json-develop/include/nlohmann/detail/iterators/iteration_proxy.hpp \
    backend/json-develop/include/nlohmann/detail/iterators/iterator_traits.hpp \
    backend/json-develop/include/nlohmann/detail/iterators/json_reverse_iterator.hpp \
    backend/json-develop/include/nlohmann/detail/iterators/primitive_iterator.hpp \
    backend/json-develop/include/nlohmann/detail/json_custom_base_class.hpp \
    backend/json-develop/include/nlohmann/detail/json_pointer.hpp \
    backend/json-develop/include/nlohmann/detail/json_ref.hpp \
    backend/json-develop/include/nlohmann/detail/macro_scope.hpp \
    backend/json-develop/include/nlohmann/detail/macro_unscope.hpp \
    backend/json-develop/include/nlohmann/detail/meta/call_std/begin.hpp \
    backend/json-develop/include/nlohmann/detail/meta/call_std/end.hpp \
    backend/json-develop/include/nlohmann/detail/meta/cpp_future.hpp \
    backend/json-develop/include/nlohmann/detail/meta/detected.hpp \
    backend/json-develop/include/nlohmann/detail/meta/identity_tag.hpp \
    backend/json-develop/include/nlohmann/detail/meta/is_sax.hpp \
    backend/json-develop/include/nlohmann/detail/meta/std_fs.hpp \
    backend/json-develop/include/nlohmann/detail/meta/type_traits.hpp \
    backend/json-develop/include/nlohmann/detail/meta/void_t.hpp \
    backend/json-develop/include/nlohmann/detail/output/binary_writer.hpp \
    backend/json-develop/include/nlohmann/detail/output/output_adapters.hpp \
    backend/json-develop/include/nlohmann/detail/output/serializer.hpp \
    backend/json-develop/include/nlohmann/detail/string_concat.hpp \
    backend/json-develop/include/nlohmann/detail/string_escape.hpp \
    backend/json-develop/include/nlohmann/detail/value_t.hpp \
    backend/json-develop/include/nlohmann/json.hpp \
    backend/json-develop/include/nlohmann/json_fwd.hpp \
    backend/json-develop/include/nlohmann/ordered_map.hpp \
    backend/json-develop/include/nlohmann/thirdparty/hedley/hedley.hpp \
    backend/json-develop/include/nlohmann/thirdparty/hedley/hedley_undef.hpp \
    backend/json-develop/single_include/nlohmann/json.hpp \
    backend/json-develop/single_include/nlohmann/json_fwd.hpp \
    backend/json-develop/tests/abi/config/config.hpp \
    backend/json-develop/tests/abi/diag/diag.hpp \
    backend/json-develop/tests/abi/include/nlohmann/json_v3_10_5.hpp \
    backend/json-develop/tests/cmake_target_include_directories/project/Bar.hpp \
    backend/json-develop/tests/cmake_target_include_directories/project/Foo.hpp \
    backend/json-develop/tests/src/make_test_data_available.hpp \
    backend/json-develop/tests/src/test_utils.hpp \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerCorpus.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerDefs.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerDictionary.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerExtFunctions.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerIO.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerInterface.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerInternal.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerMerge.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerMutate.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerOptions.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerRandom.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerSHA1.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerTracePC.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerUtil.h \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerValueBitMap.h \
    backend/json-develop/tests/thirdparty/doctest/doctest.h \
    backend/json-develop/tests/thirdparty/doctest/doctest_compatibility.h \
    backend/json-develop/tests/thirdparty/fifo_map/fifo_map.hpp \
    frontend/layoutswidget.h \
    frontend/mainwindow.h \
    frontend/searchMenu.h \
    frontend/menubar.h \
    frontend/simulation.h \
    frontend/editor.h \
    frontend/sensorPanel.h \
    backend/sensors.h

RESOURCES = resources.qrc \




# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    backend/json-develop/.cirrus.yml \
    backend/json-develop/.clang-format \
    backend/json-develop/.clang-tidy \
    backend/json-develop/.github/CODEOWNERS \
    backend/json-develop/.github/CODE_OF_CONDUCT.md \
    backend/json-develop/.github/CONTRIBUTING.md \
    backend/json-develop/.github/FUNDING.yml \
    backend/json-develop/.github/ISSUE_TEMPLATE/bug.yaml \
    backend/json-develop/.github/ISSUE_TEMPLATE/config.yml \
    backend/json-develop/.github/PULL_REQUEST_TEMPLATE.md \
    backend/json-develop/.github/SECURITY.md \
    backend/json-develop/.github/config.yml \
    backend/json-develop/.github/external_ci/appveyor.yml \
    backend/json-develop/.github/labeler.yml \
    backend/json-develop/.github/stale.yml \
    backend/json-develop/.github/workflows/check_amalgamation.yml \
    backend/json-develop/.github/workflows/cifuzz.yml \
    backend/json-develop/.github/workflows/codeql-analysis.yml \
    backend/json-develop/.github/workflows/comment_check_amalgamation.yml \
    backend/json-develop/.github/workflows/labeler.yml \
    backend/json-develop/.github/workflows/macos.yml \
    backend/json-develop/.github/workflows/publish_documentation.yml \
    backend/json-develop/.github/workflows/ubuntu.yml \
    backend/json-develop/.github/workflows/windows.yml \
    backend/json-develop/.gitignore \
    backend/json-develop/.lgtm.yml \
    backend/json-develop/.reuse/README.md \
    backend/json-develop/.reuse/dep5 \
    backend/json-develop/.reuse/templates/json.jinja2 \
    backend/json-develop/.reuse/templates/json_support.jinja2 \
    backend/json-develop/BUILD.bazel \
    backend/json-develop/CITATION.cff \
    backend/json-develop/CMakeLists.txt \
    backend/json-develop/ChangeLog.md \
    backend/json-develop/LICENSE.MIT \
    backend/json-develop/LICENSES/Apache-2.0.txt \
    backend/json-develop/LICENSES/BSD-3-Clause.txt \
    backend/json-develop/LICENSES/GPL-3.0-only.txt \
    backend/json-develop/LICENSES/MIT.txt \
    backend/json-develop/Package.swift \
    backend/json-develop/README.md \
    backend/json-develop/WORKSPACE.bazel \
    backend/json-develop/cmake/ci.cmake \
    backend/json-develop/cmake/config.cmake.in \
    backend/json-develop/cmake/download_test_data.cmake \
    backend/json-develop/cmake/nlohmann_jsonConfigVersion.cmake.in \
    backend/json-develop/cmake/pkg-config.pc.in \
    backend/json-develop/cmake/scripts/gen_bazel_build_file.cmake \
    backend/json-develop/cmake/test.cmake \
    backend/json-develop/docs/README.md \
    backend/json-develop/docs/avatars.png \
    backend/json-develop/docs/docset/Info.plist \
    backend/json-develop/docs/docset/README.md \
    backend/json-develop/docs/docset/docSet.sql \
    backend/json-develop/docs/docset/docset.json \
    backend/json-develop/docs/docset/icon.png \
    backend/json-develop/docs/docset/icon@2x.png \
    backend/json-develop/docs/examples/README.output \
    backend/json-develop/docs/examples/accept__string.output \
    backend/json-develop/docs/examples/array.output \
    backend/json-develop/docs/examples/array_t.output \
    backend/json-develop/docs/examples/at__json_pointer.output \
    backend/json-develop/docs/examples/at__json_pointer_const.output \
    backend/json-develop/docs/examples/at__keytype.c++17.output \
    backend/json-develop/docs/examples/at__keytype_const.c++17.output \
    backend/json-develop/docs/examples/at__object_t_key_type.output \
    backend/json-develop/docs/examples/at__object_t_key_type_const.output \
    backend/json-develop/docs/examples/at__size_type.output \
    backend/json-develop/docs/examples/at__size_type_const.output \
    backend/json-develop/docs/examples/back.output \
    backend/json-develop/docs/examples/basic_json__CompatibleType.output \
    backend/json-develop/docs/examples/basic_json__InputIt_InputIt.output \
    backend/json-develop/docs/examples/basic_json__basic_json.output \
    backend/json-develop/docs/examples/basic_json__copyassignment.output \
    backend/json-develop/docs/examples/basic_json__list_init_t.output \
    backend/json-develop/docs/examples/basic_json__moveconstructor.output \
    backend/json-develop/docs/examples/basic_json__nullptr_t.output \
    backend/json-develop/docs/examples/basic_json__size_type_basic_json.output \
    backend/json-develop/docs/examples/basic_json__value_t.output \
    backend/json-develop/docs/examples/begin.output \
    backend/json-develop/docs/examples/binary.output \
    backend/json-develop/docs/examples/binary_t.output \
    backend/json-develop/docs/examples/boolean_t.output \
    backend/json-develop/docs/examples/byte_container_with_subtype__byte_container_with_subtype.output \
    backend/json-develop/docs/examples/byte_container_with_subtype__clear_subtype.output \
    backend/json-develop/docs/examples/byte_container_with_subtype__has_subtype.output \
    backend/json-develop/docs/examples/byte_container_with_subtype__set_subtype.output \
    backend/json-develop/docs/examples/byte_container_with_subtype__subtype.output \
    backend/json-develop/docs/examples/cbegin.output \
    backend/json-develop/docs/examples/cbor_tag_handler_t.output \
    backend/json-develop/docs/examples/cend.output \
    backend/json-develop/docs/examples/clear.output \
    backend/json-develop/docs/examples/contains__json_pointer.output \
    backend/json-develop/docs/examples/contains__keytype.c++17.output \
    backend/json-develop/docs/examples/contains__object_t_key_type.output \
    backend/json-develop/docs/examples/count__keytype.c++17.output \
    backend/json-develop/docs/examples/count__object_t_key_type.output \
    backend/json-develop/docs/examples/crbegin.output \
    backend/json-develop/docs/examples/crend.output \
    backend/json-develop/docs/examples/default_object_comparator_t.output \
    backend/json-develop/docs/examples/diagnostics_extended.output \
    backend/json-develop/docs/examples/diagnostics_standard.output \
    backend/json-develop/docs/examples/diff.output \
    backend/json-develop/docs/examples/dump.output \
    backend/json-develop/docs/examples/emplace.output \
    backend/json-develop/docs/examples/emplace_back.output \
    backend/json-develop/docs/examples/empty.output \
    backend/json-develop/docs/examples/end.output \
    backend/json-develop/docs/examples/erase__IteratorType.output \
    backend/json-develop/docs/examples/erase__IteratorType_IteratorType.output \
    backend/json-develop/docs/examples/erase__keytype.c++17.output \
    backend/json-develop/docs/examples/erase__object_t_key_type.output \
    backend/json-develop/docs/examples/erase__size_type.output \
    backend/json-develop/docs/examples/error_handler_t.output \
    backend/json-develop/docs/examples/exception.output \
    backend/json-develop/docs/examples/find__keytype.c++17.output \
    backend/json-develop/docs/examples/find__object_t_key_type.output \
    backend/json-develop/docs/examples/flatten.output \
    backend/json-develop/docs/examples/from_bjdata.output \
    backend/json-develop/docs/examples/from_bson.output \
    backend/json-develop/docs/examples/from_cbor.output \
    backend/json-develop/docs/examples/from_json__default_constructible.output \
    backend/json-develop/docs/examples/from_json__non_default_constructible.output \
    backend/json-develop/docs/examples/from_msgpack.output \
    backend/json-develop/docs/examples/from_ubjson.output \
    backend/json-develop/docs/examples/front.output \
    backend/json-develop/docs/examples/get__PointerType.output \
    backend/json-develop/docs/examples/get__ValueType_const.output \
    backend/json-develop/docs/examples/get_allocator.output \
    backend/json-develop/docs/examples/get_binary.output \
    backend/json-develop/docs/examples/get_ptr.output \
    backend/json-develop/docs/examples/get_ref.output \
    backend/json-develop/docs/examples/get_to.output \
    backend/json-develop/docs/examples/insert.output \
    backend/json-develop/docs/examples/insert__count.output \
    backend/json-develop/docs/examples/insert__ilist.output \
    backend/json-develop/docs/examples/insert__range.output \
    backend/json-develop/docs/examples/insert__range_object.output \
    backend/json-develop/docs/examples/invalid_iterator.output \
    backend/json-develop/docs/examples/is_array.output \
    backend/json-develop/docs/examples/is_binary.output \
    backend/json-develop/docs/examples/is_boolean.output \
    backend/json-develop/docs/examples/is_discarded.output \
    backend/json-develop/docs/examples/is_null.output \
    backend/json-develop/docs/examples/is_number.output \
    backend/json-develop/docs/examples/is_number_float.output \
    backend/json-develop/docs/examples/is_number_integer.output \
    backend/json-develop/docs/examples/is_number_unsigned.output \
    backend/json-develop/docs/examples/is_object.output \
    backend/json-develop/docs/examples/is_primitive.output \
    backend/json-develop/docs/examples/is_string.output \
    backend/json-develop/docs/examples/is_structured.output \
    backend/json-develop/docs/examples/items.output \
    backend/json-develop/docs/examples/json_base_class_t.output \
    backend/json-develop/docs/examples/json_lines.output \
    backend/json-develop/docs/examples/json_pointer.output \
    backend/json-develop/docs/examples/json_pointer__back.output \
    backend/json-develop/docs/examples/json_pointer__empty.output \
    backend/json-develop/docs/examples/json_pointer__operator__equal.output \
    backend/json-develop/docs/examples/json_pointer__operator__equal_stringtype.output \
    backend/json-develop/docs/examples/json_pointer__operator__notequal.output \
    backend/json-develop/docs/examples/json_pointer__operator__notequal_stringtype.output \
    backend/json-develop/docs/examples/json_pointer__operator_add.output \
    backend/json-develop/docs/examples/json_pointer__operator_add_binary.output \
    backend/json-develop/docs/examples/json_pointer__operator_string_t.output \
    backend/json-develop/docs/examples/json_pointer__parent_pointer.output \
    backend/json-develop/docs/examples/json_pointer__pop_back.output \
    backend/json-develop/docs/examples/json_pointer__push_back.output \
    backend/json-develop/docs/examples/json_pointer__string_t.output \
    backend/json-develop/docs/examples/json_pointer__to_string.output \
    backend/json-develop/docs/examples/max_size.output \
    backend/json-develop/docs/examples/merge_patch.output \
    backend/json-develop/docs/examples/meta.output \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_explicit.output \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_macro.output \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_only_serialize_explicit.output \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_only_serialize_macro.output \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_with_default_explicit.output \
    backend/json-develop/docs/examples/nlohmann_define_type_intrusive_with_default_macro.output \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_explicit.output \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_macro.output \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_only_serialize_explicit.output \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_only_serialize_macro.output \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_with_default_explicit.output \
    backend/json-develop/docs/examples/nlohmann_define_type_non_intrusive_with_default_macro.output \
    backend/json-develop/docs/examples/nlohmann_json_namespace.output \
    backend/json-develop/docs/examples/nlohmann_json_namespace_begin.c++17.output \
    backend/json-develop/docs/examples/nlohmann_json_namespace_no_version.output \
    backend/json-develop/docs/examples/nlohmann_json_serialize_enum.output \
    backend/json-develop/docs/examples/nlohmann_json_serialize_enum_2.output \
    backend/json-develop/docs/examples/nlohmann_json_version.output \
    backend/json-develop/docs/examples/number_float_t.output \
    backend/json-develop/docs/examples/number_integer_t.output \
    backend/json-develop/docs/examples/number_unsigned_t.output \
    backend/json-develop/docs/examples/object.output \
    backend/json-develop/docs/examples/object_comparator_t.output \
    backend/json-develop/docs/examples/object_t.output \
    backend/json-develop/docs/examples/operator__ValueType.output \
    backend/json-develop/docs/examples/operator__equal.output \
    backend/json-develop/docs/examples/operator__equal__nullptr_t.output \
    backend/json-develop/docs/examples/operator__equal__specializations.output \
    backend/json-develop/docs/examples/operator__greater.output \
    backend/json-develop/docs/examples/operator__greaterequal.output \
    backend/json-develop/docs/examples/operator__less.output \
    backend/json-develop/docs/examples/operator__lessequal.output \
    backend/json-develop/docs/examples/operator__notequal.output \
    backend/json-develop/docs/examples/operator__notequal__nullptr_t.output \
    backend/json-develop/docs/examples/operator__value_t.output \
    backend/json-develop/docs/examples/operator_array__json_pointer.output \
    backend/json-develop/docs/examples/operator_array__json_pointer_const.output \
    backend/json-develop/docs/examples/operator_array__keytype.c++17.output \
    backend/json-develop/docs/examples/operator_array__keytype_const.c++17.output \
    backend/json-develop/docs/examples/operator_array__object_t_key_type.output \
    backend/json-develop/docs/examples/operator_array__object_t_key_type_const.output \
    backend/json-develop/docs/examples/operator_array__size_type.output \
    backend/json-develop/docs/examples/operator_array__size_type_const.output \
    backend/json-develop/docs/examples/operator_deserialize.output \
    backend/json-develop/docs/examples/operator_literal_json.output \
    backend/json-develop/docs/examples/operator_literal_json_pointer.output \
    backend/json-develop/docs/examples/operator_ltlt__basic_json.output \
    backend/json-develop/docs/examples/operator_ltlt__json_pointer.output \
    backend/json-develop/docs/examples/operator_spaceship__const_reference.c++20.output \
    backend/json-develop/docs/examples/operator_spaceship__scalartype.c++20.output \
    backend/json-develop/docs/examples/ordered_json.output \
    backend/json-develop/docs/examples/ordered_map.output \
    backend/json-develop/docs/examples/other_error.output \
    backend/json-develop/docs/examples/out_of_range.output \
    backend/json-develop/docs/examples/parse__allow_exceptions.output \
    backend/json-develop/docs/examples/parse__array__parser_callback_t.output \
    backend/json-develop/docs/examples/parse__contiguouscontainer__parser_callback_t.output \
    backend/json-develop/docs/examples/parse__istream__parser_callback_t.output \
    backend/json-develop/docs/examples/parse__iterator_pair.link \
    backend/json-develop/docs/examples/parse__iterator_pair.output \
    backend/json-develop/docs/examples/parse__pointers.link \
    backend/json-develop/docs/examples/parse__pointers.output \
    backend/json-develop/docs/examples/parse__string__parser_callback_t.output \
    backend/json-develop/docs/examples/parse_error.output \
    backend/json-develop/docs/examples/patch.output \
    backend/json-develop/docs/examples/patch_inplace.output \
    backend/json-develop/docs/examples/push_back.output \
    backend/json-develop/docs/examples/push_back__initializer_list.output \
    backend/json-develop/docs/examples/push_back__object_t__value.output \
    backend/json-develop/docs/examples/rbegin.output \
    backend/json-develop/docs/examples/rend.output \
    backend/json-develop/docs/examples/sax_parse.output \
    backend/json-develop/docs/examples/sax_parse__binary.output \
    backend/json-develop/docs/examples/size.output \
    backend/json-develop/docs/examples/std_hash.output \
    backend/json-develop/docs/examples/std_swap.output \
    backend/json-develop/docs/examples/string_t.output \
    backend/json-develop/docs/examples/swap__array_t.output \
    backend/json-develop/docs/examples/swap__binary_t.output \
    backend/json-develop/docs/examples/swap__object_t.output \
    backend/json-develop/docs/examples/swap__reference.output \
    backend/json-develop/docs/examples/swap__string_t.output \
    backend/json-develop/docs/examples/to_bjdata.output \
    backend/json-develop/docs/examples/to_bson.output \
    backend/json-develop/docs/examples/to_cbor.output \
    backend/json-develop/docs/examples/to_json.output \
    backend/json-develop/docs/examples/to_msgpack.output \
    backend/json-develop/docs/examples/to_string.output \
    backend/json-develop/docs/examples/to_ubjson.output \
    backend/json-develop/docs/examples/type.output \
    backend/json-develop/docs/examples/type_error.output \
    backend/json-develop/docs/examples/type_name.output \
    backend/json-develop/docs/examples/unflatten.output \
    backend/json-develop/docs/examples/update.output \
    backend/json-develop/docs/examples/update__range.output \
    backend/json-develop/docs/examples/value__json_ptr.output \
    backend/json-develop/docs/examples/value__keytype.c++17.output \
    backend/json-develop/docs/examples/value__object_t_key_type.output \
    backend/json-develop/docs/json.gif \
    backend/json-develop/docs/mkdocs/docs/api/adl_serializer/from_json.md \
    backend/json-develop/docs/mkdocs/docs/api/adl_serializer/index.md \
    backend/json-develop/docs/mkdocs/docs/api/adl_serializer/to_json.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/accept.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/array.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/array_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/at.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/back.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/basic_json.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/begin.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/binary.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/binary_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/boolean_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/cbegin.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/cbor_tag_handler_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/cend.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/clear.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/contains.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/count.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/crbegin.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/crend.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/default_object_comparator_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/diff.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/dump.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/emplace.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/emplace_back.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/empty.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/end.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/erase.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/error_handler_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/exception.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/find.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/flatten.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/from_bjdata.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/from_bson.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/from_cbor.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/from_msgpack.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/from_ubjson.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/front.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/get.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/get_allocator.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/get_binary.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/get_ptr.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/get_ref.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/get_to.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/index.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/input_format_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/insert.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/invalid_iterator.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_array.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_binary.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_boolean.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_discarded.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_null.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_number.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_number_float.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_number_integer.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_number_unsigned.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_object.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_primitive.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_string.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/is_structured.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/items.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/json_base_class_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/json_serializer.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/max_size.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/merge_patch.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/meta.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/number_float_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/number_integer_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/number_unsigned_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/object.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/object_comparator_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/object_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator+=.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator=.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator[].md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_ValueType.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_eq.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_ge.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_gt.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_le.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_lt.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_ne.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_spaceship.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/operator_value_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/other_error.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/out_of_range.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/parse.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/parse_error.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/parse_event_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/parser_callback_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/patch.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/patch_inplace.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/push_back.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/rbegin.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/rend.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/sax_parse.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/size.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/std_hash.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/std_swap.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/string_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/swap.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/to_bjdata.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/to_bson.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/to_cbor.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/to_msgpack.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/to_string.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/to_ubjson.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/type.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/type_error.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/type_name.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/unflatten.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/update.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/value.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/value_t.md \
    backend/json-develop/docs/mkdocs/docs/api/basic_json/~basic_json.md \
    backend/json-develop/docs/mkdocs/docs/api/byte_container_with_subtype/byte_container_with_subtype.md \
    backend/json-develop/docs/mkdocs/docs/api/byte_container_with_subtype/clear_subtype.md \
    backend/json-develop/docs/mkdocs/docs/api/byte_container_with_subtype/has_subtype.md \
    backend/json-develop/docs/mkdocs/docs/api/byte_container_with_subtype/index.md \
    backend/json-develop/docs/mkdocs/docs/api/byte_container_with_subtype/set_subtype.md \
    backend/json-develop/docs/mkdocs/docs/api/byte_container_with_subtype/subtype.md \
    backend/json-develop/docs/mkdocs/docs/api/json.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/back.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/empty.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/index.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/json_pointer.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/operator_eq.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/operator_ne.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/operator_slash.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/operator_slasheq.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/operator_string_t.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/parent_pointer.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/pop_back.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/push_back.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/string_t.md \
    backend/json-develop/docs/mkdocs/docs/api/json_pointer/to_string.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/binary.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/boolean.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/end_array.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/end_object.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/index.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/key.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/null.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/number_float.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/number_integer.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/number_unsigned.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/parse_error.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/start_array.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/start_object.md \
    backend/json-develop/docs/mkdocs/docs/api/json_sax/string.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/index.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_assert.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_diagnostics.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_disable_enum_serialization.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_has_cpp_11.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_has_filesystem.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_has_ranges.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_has_static_rtti.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_has_three_way_comparison.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_no_io.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_noexception.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_skip_library_version_check.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_skip_unsupported_compiler_check.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_throw_user.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_use_global_udls.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_use_implicit_conversions.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/json_use_legacy_discarded_value_comparison.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_define_type_intrusive.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_define_type_non_intrusive.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_json_namespace.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_json_namespace_begin.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_json_namespace_no_version.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_json_serialize_enum.md \
    backend/json-develop/docs/mkdocs/docs/api/macros/nlohmann_json_version_major.md \
    backend/json-develop/docs/mkdocs/docs/api/operator_gtgt.md \
    backend/json-develop/docs/mkdocs/docs/api/operator_literal_json.md \
    backend/json-develop/docs/mkdocs/docs/api/operator_literal_json_pointer.md \
    backend/json-develop/docs/mkdocs/docs/api/operator_ltlt.md \
    backend/json-develop/docs/mkdocs/docs/api/ordered_json.md \
    backend/json-develop/docs/mkdocs/docs/api/ordered_map.md \
    backend/json-develop/docs/mkdocs/docs/css/custom.css \
    backend/json-develop/docs/mkdocs/docs/features/arbitrary_types.md \
    backend/json-develop/docs/mkdocs/docs/features/assertions.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_formats/bjdata.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_formats/bson.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_formats/cbor.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_formats/index.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_formats/messagepack.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_formats/ubjson.md \
    backend/json-develop/docs/mkdocs/docs/features/binary_values.md \
    backend/json-develop/docs/mkdocs/docs/features/comments.md \
    backend/json-develop/docs/mkdocs/docs/features/element_access/checked_access.md \
    backend/json-develop/docs/mkdocs/docs/features/element_access/default_value.md \
    backend/json-develop/docs/mkdocs/docs/features/element_access/index.md \
    backend/json-develop/docs/mkdocs/docs/features/element_access/unchecked_access.md \
    backend/json-develop/docs/mkdocs/docs/features/enum_conversion.md \
    backend/json-develop/docs/mkdocs/docs/features/iterators.md \
    backend/json-develop/docs/mkdocs/docs/features/json_patch.md \
    backend/json-develop/docs/mkdocs/docs/features/json_pointer.md \
    backend/json-develop/docs/mkdocs/docs/features/macros.md \
    backend/json-develop/docs/mkdocs/docs/features/merge_patch.md \
    backend/json-develop/docs/mkdocs/docs/features/namespace.md \
    backend/json-develop/docs/mkdocs/docs/features/object_order.md \
    backend/json-develop/docs/mkdocs/docs/features/parsing/index.md \
    backend/json-develop/docs/mkdocs/docs/features/parsing/json_lines.md \
    backend/json-develop/docs/mkdocs/docs/features/parsing/parse_exceptions.md \
    backend/json-develop/docs/mkdocs/docs/features/parsing/parser_callbacks.md \
    backend/json-develop/docs/mkdocs/docs/features/parsing/sax_interface.md \
    backend/json-develop/docs/mkdocs/docs/features/types/index.md \
    backend/json-develop/docs/mkdocs/docs/features/types/number_handling.md \
    backend/json-develop/docs/mkdocs/docs/home/code_of_conduct.md \
    backend/json-develop/docs/mkdocs/docs/home/design_goals.md \
    backend/json-develop/docs/mkdocs/docs/home/exceptions.md \
    backend/json-develop/docs/mkdocs/docs/home/faq.md \
    backend/json-develop/docs/mkdocs/docs/home/license.md \
    backend/json-develop/docs/mkdocs/docs/home/releases.md \
    backend/json-develop/docs/mkdocs/docs/home/sponsors.md \
    backend/json-develop/docs/mkdocs/docs/images/callback_events.png \
    backend/json-develop/docs/mkdocs/docs/images/json_syntax_number.png \
    backend/json-develop/docs/mkdocs/docs/images/range-begin-end.svg \
    backend/json-develop/docs/mkdocs/docs/images/range-rbegin-rend.svg \
    backend/json-develop/docs/mkdocs/docs/index.md \
    backend/json-develop/docs/mkdocs/docs/integration/cmake.md \
    backend/json-develop/docs/mkdocs/docs/integration/conan/CMakeLists.txt \
    backend/json-develop/docs/mkdocs/docs/integration/conan/Conanfile.txt \
    backend/json-develop/docs/mkdocs/docs/integration/index.md \
    backend/json-develop/docs/mkdocs/docs/integration/migration_guide.md \
    backend/json-develop/docs/mkdocs/docs/integration/package_managers.md \
    backend/json-develop/docs/mkdocs/docs/integration/pkg-config.md \
    backend/json-develop/docs/mkdocs/docs/integration/vcpkg/CMakeLists.txt \
    backend/json-develop/docs/mkdocs/mkdocs.yml \
    backend/json-develop/docs/mkdocs/requirements.txt \
    backend/json-develop/docs/mkdocs/scripts/check_structure.py \
    backend/json-develop/docs/usages/ios.png \
    backend/json-develop/docs/usages/macos.png \
    backend/json-develop/meson.build \
    backend/json-develop/nlohmann_json.natvis \
    backend/json-develop/tests/CMakeLists.txt \
    backend/json-develop/tests/abi/CMakeLists.txt \
    backend/json-develop/tests/abi/config/CMakeLists.txt \
    backend/json-develop/tests/abi/diag/CMakeLists.txt \
    backend/json-develop/tests/abi/inline_ns/CMakeLists.txt \
    backend/json-develop/tests/benchmarks/CMakeLists.txt \
    backend/json-develop/tests/cmake_add_subdirectory/CMakeLists.txt \
    backend/json-develop/tests/cmake_add_subdirectory/project/CMakeLists.txt \
    backend/json-develop/tests/cmake_fetch_content/CMakeLists.txt \
    backend/json-develop/tests/cmake_fetch_content/project/CMakeLists.txt \
    backend/json-develop/tests/cmake_fetch_content2/CMakeLists.txt \
    backend/json-develop/tests/cmake_fetch_content2/project/CMakeLists.txt \
    backend/json-develop/tests/cmake_import/CMakeLists.txt \
    backend/json-develop/tests/cmake_import/project/CMakeLists.txt \
    backend/json-develop/tests/cmake_import_minver/CMakeLists.txt \
    backend/json-develop/tests/cmake_import_minver/project/CMakeLists.txt \
    backend/json-develop/tests/cmake_target_include_directories/CMakeLists.txt \
    backend/json-develop/tests/cmake_target_include_directories/project/CMakeLists.txt \
    backend/json-develop/tests/cuda_example/CMakeLists.txt \
    backend/json-develop/tests/cuda_example/json_cuda.cu \
    backend/json-develop/tests/fuzzing.md \
    backend/json-develop/tests/reports/2016-08-29-fuzz/exec_speed.png \
    backend/json-develop/tests/reports/2016-08-29-fuzz/fuzz.tiff \
    backend/json-develop/tests/reports/2016-08-29-fuzz/high_freq.png \
    backend/json-develop/tests/reports/2016-08-29-fuzz/index.html \
    backend/json-develop/tests/reports/2016-08-29-fuzz/low_freq.png \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/README.md \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/conformance_Nlohmann (C++11).md \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/conformance_overall_Result.png \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_1._Parse_Memory_(byte).png \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_1._Parse_Time_(ms).png \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_2._Stringify_Time_(ms).png \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_3._Prettify_Time_(ms).png \
    backend/json-develop/tests/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_7._Code_size_FileSize_(byte).png \
    backend/json-develop/tests/reports/2016-10-02-fuzz/exec_speed.png \
    backend/json-develop/tests/reports/2016-10-02-fuzz/fuzz.tiff \
    backend/json-develop/tests/reports/2016-10-02-fuzz/high_freq.png \
    backend/json-develop/tests/reports/2016-10-02-fuzz/index.html \
    backend/json-develop/tests/reports/2016-10-02-fuzz/low_freq.png \
    backend/json-develop/tests/thirdparty/Fuzzer/CMakeLists.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerExtFunctions.def \
    backend/json-develop/tests/thirdparty/Fuzzer/FuzzerFlags.def \
    backend/json-develop/tests/thirdparty/Fuzzer/README.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/build.sh \
    backend/json-develop/tests/thirdparty/Fuzzer/cxx.dict \
    backend/json-develop/tests/thirdparty/Fuzzer/test/CMakeLists.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/test/afl-driver-extra-stats.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/afl-driver-stderr.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/caller-callee.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/coverage.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/dict1.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/test/dump_coverage.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-customcrossover.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-custommutator.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-dict.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-dirs.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-fdmask.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-finalstats.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-flags.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-jobs.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-leak.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-oom-with-profile.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-oom.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-printcovpcs.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-runs.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-seed.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-segv.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-singleinputs.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-threaded.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-timeout.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-traces-hooks.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer-ubsan.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/fuzzer.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/hi.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/test/lit.cfg \
    backend/json-develop/tests/thirdparty/Fuzzer/test/lit.site.cfg.in \
    backend/json-develop/tests/thirdparty/Fuzzer/test/merge.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/minimize_crash.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/no-coverage/CMakeLists.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/test/repeated-bytes.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/shrink.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/simple-cmp.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/standalone.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/swap-cmp.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/trace-malloc.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/ubsan/CMakeLists.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/test/ulimit.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/uninstrumented/CMakeLists.txt \
    backend/json-develop/tests/thirdparty/Fuzzer/test/unit/lit.cfg \
    backend/json-develop/tests/thirdparty/Fuzzer/test/unit/lit.site.cfg.in \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-cmp.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-cmp2.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-cmp3.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-cmp4.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-div.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-load.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-mem.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-set.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-strcmp.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-strncmp.test \
    backend/json-develop/tests/thirdparty/Fuzzer/test/value-profile-switch.test \
    backend/json-develop/tests/thirdparty/imapdl/filterbr.py \
    backend/json-develop/tools/amalgamate/CHANGES.md \
    backend/json-develop/tools/amalgamate/README.md \
    backend/json-develop/tools/amalgamate/amalgamate.py \
    backend/json-develop/tools/amalgamate/config_json.json \
    backend/json-develop/tools/amalgamate/config_json_fwd.json \
    backend/json-develop/tools/gdb_pretty_printer/README.md \
    backend/json-develop/tools/gdb_pretty_printer/nlohmann-json.py \
    backend/json-develop/tools/generate_natvis/README.md \
    backend/json-develop/tools/generate_natvis/generate_natvis.py \
    backend/json-develop/tools/generate_natvis/nlohmann_json.natvis.j2 \
    backend/json-develop/tools/serve_header/README.md \
    backend/json-develop/tools/serve_header/demo.png \
    backend/json-develop/tools/serve_header/requirements.txt \
    backend/json-develop/tools/serve_header/serve_header.py \
    backend/json-develop/tools/serve_header/serve_header.yml.example \
    backend/json-develop/wsjcpp.yml \
    resources/dati.json
